spring:
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/clienteDB?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
